config/routes.rb
Rails.application.routes.draw do
  resources :users # Routes pour les utilisateurs (/users, /users/new, /users/:id, /users/:id/edit)
  resources :trips # Routes pour les voyages (/trips, /trips/new, /trips/:id, /trips/:id/edit)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    before_action :set_trip, only: [:show, :edit, :update, :destroy]
    
    # GET /trips
    def index
        @trips = Trip.all
    end

    # GET /trips/1
    def show
    end

    # GET /trips/new
    def new
        @trip = Trip.new
    end

    # GET /trips/1/edit
    def edit
    end

    # POST /trips
    def create
        @trip = Trip.new(trip_params)

        if @trip.save
            redirect_to @trip, notice: 'Trip was successfully created.'
        else
            render :new
        end
    end

    # PATCH/PUT /trips/1
    def update
        if @trip.update(trip_params)
            redirect_to @trip, notice: 'Trip was successfully updated.'
        else
            render :edit
        end
    end

    # DELETE /trips/1
    def destroy
        @trip.destroy
        redirect_to trips_url, notice: 'Trip was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_trip
        @trip = Trip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trip_params
        params.require(:trip).permit(:destination, :description, :start_date, :end_date, :user_id)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:nom, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelogue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/trips/edit.html.erb
<div class="overflow-y-auto overflow-x-hidden fixed flex top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <div class="relative p-4 bg-white rounded-lg shadow :bg-gray-800 sm:p-5">
            <div class="flex justify-between items-center pb-4 mb-4 rounded-t border-b sm:mb-5 :border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 :text-white">Modifier un voyage</h3>
                <div onclick="window.location.href='<%= trips_path %>'" class="cursor-pointer text-gray-500 hover:text-gray-700 :text-gray-400 :hover:text-gray-200">
                    Annuler
                </div>
            </div>
            <%= render 'form', trip: @trip %>
        </div>
    </div>
</div>

app/views/trips/index.html.erb
<section class=" :bg-gray-900 p-3 sm:p-5 antialiased">
    <div class="mx-auto max-w-screen-xl px-4 lg:px-12">
        <div class="bg-white :bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
            <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
                <div class="w-full md:w-1/2">
                    <%# <form class="flex items-center">
                        <label for="simple-search" class="sr-only">Search</label>
                        <div class="relative w-full">
                            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                <svg aria-hidden="true" class="w-5 h-5 text-gray-500 :text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                                </svg>
                            </div>
                            <input type="text" id="simple-search" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 p-2 :bg-gray-700 :border-gray-600 :placeholder-gray-400 :text-white :focus:ring-primary-500 :focus:border-primary-500" placeholder="Search" required="">
                        </div>
                    </form> %>
                </div>
                <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
                    <%= link_to "Voir les utilisateurs", '/users', class: "flex items-center justify-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 :bg-primary-600 :hover:bg-primary-700 focus:outline-none :focus:ring-primary-800" %>
                    <button type="button" onclick="window.location.href='<%= new_trip_path %>'"
                    class="flex items-center justify-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 :bg-primary-600 :hover:bg-primary-700 focus:outline-none :focus:ring-primary-800">
                        <svg class="h-3.5 w-3.5 mr-2" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                            <path clip-rule="evenodd" fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
                        </svg>
                        Ajouter un voyage
                    </button>
                </div>
            </div>
            <div class="overflow-x-auto">
                <table class="w-full text-sm text-left text-gray-500 :text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 :bg-gray-700 :text-gray-400">
                        <tr>
                            <th scope="col" class="px-4 py-4">
                                Destination
                            </th>
                            <th scope="col" class="px-4 py-4">
                                Description
                            </th>
                            <th scope="col" class="px-4 py-4">
                                Date de départ
                            </th>
                            <th scope="col" class="px-4 py-4">
                                Date de retour
                            </th>
                            <th scope="col" class="px-4 py-4">
                                Utilisateur
                            </th>
                            <th scope="col" class="px-4 py-4">
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @trips.each do |trip| %>
                            <tr class="border-b :border-gray-700">
                                <th scope="row" class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap :text-white">
                                    <%= trip.destination %>
                                </th>
                                <td class="px-4 py-3">
                                    <%= trip.description %>
                                </td>
                                <td class="px-4 py-3">
                                    <%= trip.start_date.strftime("%d/%m/%Y") %>
                                </td>
                                <td class="px-4 py-3">
                                    <%= trip.end_date.strftime("%d/%m/%Y") %>
                                </td>
                                <td class="px-4 py-3">
                                    <%= trip.user.nom %>
                                </td>


                                <td class="px-4 py-3 flex items-center justify-end">
                                    <button type="button" onclick="window.location.href='<%= edit_trip_path(trip) %>'"
                                    class="flex w-full items-center py-2 px-4 hover:bg-gray-100 :hover:bg-gray-600 :hover:text-white text-gray-700 :text-gray-200">
                                        <svg class="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                            <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z" />
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" />
                                        </svg>
                                        Modifier
                                    </button>
                                    <button type="button" onclick="window.location.href='<%= trip_path(trip) %>'"
                                    class="flex w-full items-center py-2 px-4 hover:bg-gray-100 :hover:bg-gray-600 :hover:text-white text-gray-700 :text-gray-200">
                                        <svg class="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                            <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" />
                                        </svg>
                                        Afficher
                                    </button>
                                    <%= form_with(model: trip, method: :delete, local: false) do |form| %>
                                        <%= form.submit "Supprimer",
                                            class: "flex w-full items-center py-2 px-4 hover:bg-gray-100 :hover:bg-gray-600 text-red-500 :hover:text-red-400" %>
                                    <% end %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <nav class="flex flex-col md:flex-row justify-between items-start md:items-center space-y-3 md:space-y-0 p-4" aria-label="Table navigation">
                <span class="text-sm font-normal text-gray-500 :text-gray-400">
                    Nombre de voyages:
                    <span class="
                    font-medium
                    text-gray-900
                    :text-white

                    ">
                    <%= @trips.count %></span>
                </span>
            </nav>
        </div>
    </div>
</section>

app/views/trips/new.html.erb
<div class="overflow-y-auto overflow-x-hidden fixed flex top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <div class="relative p-4 bg-white rounded-lg shadow :bg-gray-800 sm:p-5">
            <div class="flex justify-between items-center pb-4 mb-4 rounded-t border-b sm:mb-5 :border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 :text-white">Ajouter un voyage</h3>
                <div onclick="window.location.href='<%= trips_path %>'" class="cursor-pointer text-gray-500 hover:text-gray-700 :text-gray-400 :hover:text-gray-200">
                    Annuler
                </div>
            </div>
            <%= render 'form', trip: @trip %>
        </div>
    </div>
</div>

app/views/trips/show.html.erb
<div class="overflow-y-auto overflow-x-hidden fixed flex top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <div class="relative p-4 bg-white rounded-lg shadow :bg-gray-800 sm:p-5">
            <div class="flex justify-between items-center pb-4 mb-4 rounded-t border-b sm:mb-5 :border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 :text-white">Afficher un voyage</h3>
                <div onclick="window.location.href='<%= trips_path %>'" class="cursor-pointer text-gray-500 hover:text-gray-700 :text-gray-400 :hover:text-gray-200">
                    Annuler
                </div>
            </div>
            <%= form_with(model: @trip, local: true, data: { turbo: false }) do |form| %>
                <div class="grid gap-4 mb-4 sm:grid-cols-2">
                    <div>
                    <%= form.label :destination, 
                        class: "block mb-2 text-sm font-medium text-gray-900 :text-white"%>
                    <%= form.text_field :destination, 
                        class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 :bg-gray-700 :border-gray-600 :placeholder-gray-400 :text-white :focus:ring-primary-500 :focus:border-primary-500", 
                        placeholder: "Destination",
                        disabled: true,
                        required: true %>        
                    </div>
                    <div>
                    <%= form.label :user_id, 
                        class: "block mb-2 text-sm font-medium text-gray-900 :text-white" %>
                    <%= form.select :user_id, 
                        User.all.map { |user| [user.nom, user.id] }, 
                        { prompt: true }, 
                        { class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 :bg-gray-700 :border-gray-600 :placeholder-gray-400 :text-white :focus:ring-primary-500 :focus:border-primary-500", 
                        disabled: true,
                        required: true } 
                    %>
                    </div>
                    <div>
                    <%= form.label :start_date, 
                        class: "block mb-2 text-sm font-medium text-gray-900 :text-white" %>
                    <%= form.date_field :start_date, 
                        class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 :bg-gray-700 :border-gray-600 :placeholder-gray-400 :text-white :focus:ring-primary-500 :focus:border-primary-500", 
                        placeholder: "Date de départ", 
                        disabled: true,
                        required: true %>
                    </div>

                    <div>
                    <%= form.label :end_date, 
                        class: "block mb-2 text-sm font-medium text-gray-900 :text-white" %>
                    <%= form.date_field :end_date,
                        class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 :bg-gray-700 :border-gray-600 :placeholder-gray-400 :text-white :focus:ring-primary-500 :focus:border-primary-500", 
                        placeholder: "Date de retour", 
                        disabled: true,
                        required: true %>
                    </div>
                    <div class="sm:col-span-2">
                    <%= form.label :description, 
                            class: "block mb-2 text-sm font-medium text-gray-900 :text-white" %>

                    <%= form.text_area :description, 
                        class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 :bg-gray-700 :border-gray-600 :placeholder-gray-400 :text-white :focus:ring-primary-500 :focus:border-primary-500", 
                        placeholder: "Description",
                        disabled: true, 
                        required: true %>
                    </div>
                </div>
                <button onclick="window.location.href='<%= edit_trip_path(@trip) %>'" type="button"
                    class="inline-flex items-center bg-green-400 text-white rounded-lg px-4 py-2.5 focus:outline-none hover:bg-green-500 focus:ring-4 focus:ring-green-300">
                    Modifier
                </button>
                <button onclick="deleteItem()" type="button"
                    class="inline-flex items-center bg-red-400 text-white rounded-lg px-4 py-2.5 focus:outline-none hover:bg-red-500 focus:ring-4 focus:ring-red-300">
                    Supprimer
                </button>
            <% end %>
        </div>
    </div>
</div>

<script>
    // J'ai fait cette fonction en JS car je n'ai pas réussi à faire fonctionner un form dans un form

    const deleteItem = () => {
        const form = new FormData();
        // J'ai ajouté cette ligne pour que la suppression fonctionne, sinon j'avais une erreur CSRF
        form.append("authenticity_token", "<%= form_authenticity_token %>");
        fetch("<%= trip_path(@trip) %>", {
            method: "DELETE",
            body: form
        }).then(() => {
            // Je redirige vers la page des utilisateurs
            window.location.href = "<%= trips_path %>";
        });
    }
</script>

app/views/users/index.html.erb
<section class=" p-3 sm:p-5 antialiased">
    <div class="mx-auto max-w-screen-xl px-4 lg:px-12">
        <div class="bg-white :bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
            <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
                <div class="w-full md:w-1/2">
                    <%# <form class="flex items-center">
                        <label for="simple-search" class="sr-only">Search</label>
                        <div class="relative w-full">
                            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                <svg aria-hidden="true" class="w-5 h-5 text-gray-500 :text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                                </svg>
                            </div>
                            <input type="text" id="simple-search" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 p-2 :bg-gray-700 :border-gray-600 :placeholder-gray-400 :text-white :focus:ring-primary-500 :focus:border-primary-500" placeholder="Search" required="">
                        </div>
                    </form> %>
                </div>
                <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">                    
                    <%= link_to "Voir les voyages", '/trips', class: "flex items-center justify-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 :bg-primary-600 :hover:bg-primary-700 focus:outline-none :focus:ring-primary-800" %>
                    <button type="button" onclick="window.location.href='<%= new_user_path %>'"
                        class="flex items-center justify-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 :bg-primary-600 :hover:bg-primary-700 focus:outline-none :focus:ring-primary-800">
                        <svg class="h-3.5 w-3.5 mr-2" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                            <path clip-rule="evenodd" fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
                        </svg>
                        Ajouter un utilisateur
                    </button>
                </div>
            </div>
            <div class="overflow-x-auto">
                <table class="w-full text-sm text-left text-gray-500 :text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 :bg-gray-700 :text-gray-400">
                        <tr>
                            <th scope="col" class="px-4 py-4">Nom</th>
                            <th scope="col" class="px-4 py-4">Mail</th>
                            <th scope="col" class="px-4 py-4">Voyages</th>
                            <th scope="col" class="px-4 py-4">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @users.each do |user| %>
                          <tr class="border-b :border-gray-700">
                            <th scope="row" class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap :text-white">
                              <%= user.nom %>
                            </th>
                            <td class="px-4 py-3">
                              <%= user.email %>
                            </td>
                            <td class="px-4 py-3">
                              <% user.trips.each do |trip| %>
                                - <%= link_to trip.destination, trip_path(trip) %>
                                <br/>
                              <% end %>
                            </td>
                            <td class="px-4 py-3 flex items-center justify-end">
                              <button type="button" onclick="window.location.href='<%= edit_user_path(user) %>'"
                              class="flex w-full items-center py-2 px-4 hover:bg-gray-100 :hover:bg-gray-600 :hover:text-white text-gray-700 :text-gray-200">
                                  <svg class="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                      <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z" />
                                      <path fill-rule="evenodd" clip-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" />
                                  </svg>
                                  Modifier
                              </button>
                              <button type="button" onclick="window.location.href='<%= user_path(user) %>'"
                              class="flex w-full items-center py-2 px-4 hover:bg-gray-100 :hover:bg-gray-600 :hover:text-white text-gray-700 :text-gray-200">
                                  <svg class="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                      <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
                                      <path fill-rule="evenodd" clip-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" />
                                  </svg>
                                  Afficher
                              </button>
                              <%= form_with(model: user, method: :delete, local: false) do |form| %>
                                  <%= form.submit "Supprimer",
                                      class: "flex w-full items-center py-2 px-4 hover:bg-gray-100 :hover:bg-gray-600 text-red-500 :hover:text-red-400" %>
                              <% end %>
                            </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
            <nav class="flex flex-col md:flex-row justify-between items-start md:items-center space-y-3 md:space-y-0 p-4" aria-label="Table navigation">
                <span class="text-sm font-normal text-gray-500 :text-gray-400">
                    Nombre d'utilisateurs:
                    <span class="
                      font-medium
                      text-gray-900
                      :text-white

                    ">
                    <%= @users.count %></span>
                </span>
            </nav>
        </div>
    </div>
</section>

app/views/users/show.html.erb
<div class="overflow-y-auto overflow-x-hidden fixed flex top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <div class="relative p-4 bg-white rounded-lg shadow :bg-gray-800 sm:p-5">
            <div class="flex justify-between items-center pb-4 mb-4 rounded-t border-b sm:mb-5 :border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 :text-white">Afficher un utilisateur</h3>
                <div onclick="window.location.href='<%= users_path %>'" class="cursor-pointer text-gray-500 hover:text-gray-700 :text-gray-400 :hover:text-gray-200">
                    Annuler
                </div>
            </div>
            <%= form_with(model: @user, local: true) do |form| %>
                <div class="grid gap-4 mb-4 sm:grid-cols-2">
                    <div>
                        <%= form.label :nom, 
                            class: "block mb-2 text-sm font-medium text-gray-900 :text-white"%>
                        <%= form.text_field :nom, 
                            disabled: true, 
                            class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 :bg-gray-700 :border-gray-600 :placeholder-gray-400 :text-white :focus:ring-primary-500 :focus:border-primary-500", 
                            placeholder: "Nom d'utilisateur", 
                            required: true %>
                    </div>
                    <div>
                        <%= form.label :email, 
                            class: "block mb-2 text-sm font-medium text-gray-900 :text-white" %>
                        <%= form.email_field :email, 
                            disabled: true, 
                            class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 :bg-gray-700 :border-gray-600 :placeholder-gray-400 :text-white :focus:ring-primary-500 :focus:border-primary-500", 
                            placeholder: "Adresse mail", 
                            required: true %>
                    </div>
                </div>
                <button onclick="window.location.href='<%= edit_user_path(@user) %>'" type="button"
                    class="inline-flex items-center bg-green-400 text-white rounded-lg px-4 py-2.5 focus:outline-none hover:bg-green-500 focus:ring-4 focus:ring-green-300">
                    Modifier
                </button>
                <button onclick="deleteItem()" type="button"
                    class="inline-flex items-center bg-red-400 text-white rounded-lg px-4 py-2.5 focus:outline-none hover:bg-red-500 focus:ring-4 focus:ring-red-300">
                    Supprimer
                </button>
            <% end %>
        </div>
    </div>
</div>

<script>
    // J'ai fait cette fonction en JS car je n'ai pas réussi à faire fonctionner un form dans un form

    const deleteItem = () => {
        const form = new FormData();
        // J'ai ajouté cette ligne pour que la suppression fonctionne, sinon j'avais une erreur CSRF
        form.append("authenticity_token", "<%= form_authenticity_token %>");
        fetch("<%= user_path(@user) %>", {
            method: "DELETE",
            body: form
        }).then(() => {
            // Je redirige vers la page des utilisateurs
            window.location.href = "<%= users_path %>";
        });
    }
</script>